### ISSUE TITLE
テーマを決める

### ISSUE THREAD

**Issue by inoh** [mls-itoc/fit-me#1]
## テーマを決める
野球のスターティングオーダーから勝ち負けを予測する

## 概要
過去のスターティングオーダーと勝ち負けを学習データとし、スターティングオーダーをもとに予測する。

**Comment by inoh** [comment]
ここに機械学習用のサンプルデータが載ってます！
https://archive.ics.uci.edu/ml/datasets/Bank+Marketing

**Comment by sasaki-vl** [comment]
とりあえず書き込めるかテスト

**Comment by inoh** [comment]
オリンピックのメダルの数を予想する

**Comment by inoh** [comment]
野球の勝率を予想する

**Comment by inoh** [comment]
- 野球のスタメンで勝ち負けを予測する
    - 過去のオーダー一覧
        - http://baseball-data.com/15/lineup/c.html
- TODO
    - スタメンに対する勝ち負けのデータがとれるか

**Comment by inoh** [comment]
- 教師データ
![image](https://cloud.githubusercontent.com/assets/1096516/15819105/2a4638ae-2c1c-11e6-8b58-548fe254a3f2.png)

**Comment by inoh** [comment]
## URLパターン
- http://2689web.com/2015/inter/2015CH.html
- http://2689web.com/2015/inter/2015CF.html
- http://2689web.com/2015/inter/2015CM.html
- http://2689web.com/2015/inter/2015CL.html
- http://2689web.com/2015/inter/2015CB.html
- http://2689web.com/2015/inter/2015CE.html
- http://2689web.com/2015/SC/2015SC.html
- http://2689web.com/2015/GC/2015GC.html
- http://2689web.com/2015/TC/2015TC.html
- http://2689web.com/2015/CD/2015CD.html
- http://2689web.com/2015/CY/2015CY.html
- http://2689web.com/2015/SC/2015SC.html
- http://2689web.com/2015/GC/2015GC.html
- http://2689web.com/2015/TC/2015TC.html
- http://2689web.com/2015/CD/2015CD.html
- http://2689web.com/2015/CY/2015CY.html
- http://2689web.com/2015/inter/2015CH.html
- http://2689web.com/2015/inter/2015CF.html
- http://2689web.com/2015/inter/2015CM.html
- http://2689web.com/2015/inter/2015CL.html
- http://2689web.com/2015/inter/2015CB.html
- http://2689web.com/2015/inter/2015CE.html

**Comment by inoh** [comment]
## パターン
http://2689web.com/2015/#{対戦チーム記号}/#{対戦チーム記号}#{連番}.html
## 引数
- 対戦チーム記号
    - 上記参照
- 連番
    - SCの場合、25までとりあえずあるのを確認

**Comment by inoh** [comment]
メンバの画像をもとに誰の画像かを判断するものを作る。
